version: "3.9"
services:
  postgres:
    image: postgres:14.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: "top_hero_service"
      POSTGRES_USER: "top_hero_service"
      POSTGRES_PASSWORD: "vc894hv9w"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432

  redis:
    image: redis:7
    ports:
      - 6379:6379

  server:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: celery -A celery_worker worker --loglevel=debug --logfile=logs/celery.log

    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
  beat:
    build: .
    command: celery -A celery_worker beat --loglevel=debug --logfile=logs/celery.log

    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  dashboard:
    build: .
    command: celery -A celery_worker  flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - worker
      - beat
