"""add best heroes model

Revision ID: 5db8053fa1d0
Revises: a3c58d258695
Create Date: 2024-07-08 21:43:05.329412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db8053fa1d0'
down_revision: Union[str, None] = 'a3c58d258695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_horoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('hero', sa.Integer(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.Column('voting', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hero'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['patch'], ['patch.number'], ),
    sa.ForeignKeyConstraint(['voting'], ['voting.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('patch_voting_index', 'best_horoes', ['patch', 'voting'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('patch_voting_index', table_name='best_horoes')
    op.drop_table('best_horoes')
    # ### end Alembic commands ###
