"""init_0001

Revision ID: a3c58d258695
Revises: 
Create Date: 2024-06-27 23:28:20.312189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c58d258695'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=True)
    op.create_table('patch',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('voting',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('top_hero', sa.Integer(), nullable=True),
    sa.Column('top_2_hero', sa.Integer(), nullable=True),
    sa.Column('top_3_hero', sa.Integer(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.Column('voting', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patch'], ['patch.number'], ),
    sa.ForeignKeyConstraint(['top_2_hero'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['top_3_hero'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['top_hero'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['voting'], ['voting.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('voting')
    op.drop_table('patch')
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###
